version: 0.2

phases:
  install:
    commands:
      - echo Installing httpd
      - sudo yum update -y
      - sudo yum install httpd -y
      - export AWS_DEFAULT_REGION=ap-south-1
  build:
    commands:
      - echo Build started on `date`
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring httpd

artifacts:
  files:
    - '**/*'
